server:
  port: 8210

logging:
  file: log/springboot.log
  level:
    com.phy.bcs.service.ifs: debug

camel:
  springboot:
    main-run-controller: true
fileprocess:
  ftp:
    host: localhost
    port: 50000
    username: dev
    password: 123456
    scan-delay: 5000
    readerCharset: "UTF-8"
    senderCharset: "UTF-8"
    reader-scanner-enable: true
    sender-scanner-enable: true
    send-local-dir: "./.ftp-send/"
    send-bak-local-dir: "./.ftp-sent-bak/"
    read-temp-local-dir:  "./.ftp-received-temp/"
    read-bak-local-dir:  "./.ftp-received-bak/"
    #send-file-pattern: '^(MPSS_){1}.*'
    send-file-pattern: '^.*_.*_.*_.*'
    #read-file-pattern: '.*(_MPSS_JB17){1}.*'
    read-file-pattern: '^.*_.*_.*'
    #HZJ向内部发送的文件夹
    hzj-send: "/HZJ/"
    #HZJ读取的文件夹
    hzj-read: "/"
    #内部向HZJ发送的文件夹
    internal-send-hzj: "/INTOHZJ/"
    #五型向26站网发送的文件夹
    tfc-send-26s: "/26S/"
    #五型向26长管发送的文件夹
    tfc-send-26m: "/26M/"
    #五型向中继中心发送的文件夹
    tfc-send-zj: "/ZJ/"
    #五型读取的文件夹
    tfc-read: "/"
    #54读取的文件夹
    ffoc-read: "/"
    passive-mode: true
    #hzj FTP服务1
    hzj-ftpserver1:
      servername: ftpserver1
      host: 172.16.5.32
      port: 21
      username: hzj1
      password: 123456
    #hzj FTP服务2
    hzj-ftpserver2:
      servername: ftpserver2
      host: 172.16.5.32
      port: 21
      username: hzj2
      password: 123456
    #hzj FTP服务3
    hzj-ftpserver3:
      servername: ftpserver3
      host: 172.16.5.32
      port: 21
      username: hzj3
      password: 123456
    #hzj FTP服务4
    hzj-ftpserver4:
      servername: ftpserver4
      host: 172.16.5.32
      port: 21
      username: hzj4
      password: 123456
    #hzj FTP服务5
    hzj-ftpserver5:
      servername: ftpserver4
      host: 172.16.5.32
      port: 21
      username: hzj5
      password: 123456
    #五型 FTP服务
    tfc-ftpserver:
      servername: ftcftpserver
      host: 172.16.5.32
      port: 21
      username: tfc
      password: 123456
    #54系统 FTP服务
    ffoc-ftpserver:
      servername: ffocftpserver
      host: 172.16.5.32
      port: 21
      username: ffoc
      password: 123456


net-application:
  #对应五型的任务号
  wxmids:
    - 0x01
    - 0x04
    - 0x02
    - 0x03
    - Hux001
    - Hux-098
    - Yuhghw
  #对应54的任务号
  wsmids:
    - 0x1001
    - 0x1002
    - 0x1003
    - 0x1004
    - Jx5-six
    - Jx449
    - Hx78-0
  #根据该参数判断当前的网络状态
  netstatustimes: 5
  #重连次数
  reconnectTimes: 5
  #超时时间（秒）
  timeout: 30
  #包大小（字节数）
  packgesize: 1024
  #五型IP与端口号配置
  tfc-system:
    ip: 172.0.0.1
    udf-port: 10003
    fep-port: 10003
    pdxp-port: 10003
  #54控制系统IP与端口号配置
  ffoc-system:
    ip: 172.16.2.55
    udf-port: 10001
    fep-port: 10001
    pdxp-port: 10001
  #26站网IP与端口号配置
  tss-system:
    ip: 127.0.0.1
    udf-port: 10004
    fep-port: 10004
    pdxp-port: 10004
  #HZJ IP与端口号配置
  hzj-system:
    ip: 172.0.0.1
    udf-port: 12301
    fep-port: 12302
    pdxp-port: 12303
  #26长管IP与端口号配置
  tsm-system:
    ip: 127.0.0.1
    udf-port: 10002
    fep-port: 10002
    pdxp-port: 10002
  #中继中心IP与端口号配置
  zj-system:
    ip: 127.0.0.1
    udf-port: 10005
    fep-port: 10005
    pdxp-port: 10005
  local-hzj-udfport: 12304
  local-tsm-fepport: 12305
  local-tsm-pdxpport: 12306
  local-tss-fepport: 12307
  local-zj-fepport: 12308


spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:dbs/sqlite_database.db
    username: root
    password: root

#Mybatis-plus配置
mybatis-plus:
  basePackage: com.phy.bcs.*.*.mapper
  mapper-locations: classpath*:/mappings/**/*Mapper.xml
  typeAliasesPackage: com.phy.bsc.*.*.model,com.phy.bcs.*.*.model.*
  #typeEnumsPackage: com.phy.mpss.*.*.model.enums
  global-config:
    banner: false
    id-type: 4
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    logic-delete-value: -1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  type-handlers-package: com.phy.bcs.service.records.model.typehandler


swagger:
  api:
    title: "BCS TITLE"
    description: "BCS API 文档"
    basepackage: "com.phy.bcs"
