server:
  port: 8210

fileprocess:
  ftp:
    host: 172.16.2.251
    port: 21
    username: yangl
    password: 20160130yl
    scan-delay: 1000
    readerCharset: "GBK"
    senderCharset: "GBK"
    reader-scanner-enable: true
    sender-scanner-enable: true
    send-local-dir: "./.ftp-send/"
    send-bak-local-dir: "./.ftp-sent-bak/"
    read-temp-local-dir:  "./.ftp-received-temp/"
    read-bak-local-dir:  "./.ftp-received-bak/"
    #send-file-pattern: '^(MPSS_){1}.*'
    send-file-pattern: '^.*_.*_.*_.*'
    #read-file-pattern: '.*(_MPSS_JB17){1}.*'
    read-file-pattern: '^.*_.*_.*'

my-application:
  #根据MIP-IP对应关系向不同的IP进行转发
  midip:
    #对应五型的任务号
    wxsites:
      - 12
      - 14
      - 15
    #对应54的任务号
    wssites:
      - 16
      - 17
      - 18
      - 19
    #根据该参数判断当前的网络状态
    netstatustimes: 5
    #重连次数
    reconnectTimes: 10
    #超时时间（秒）
    timeout: 15
    #包大小（字节数）
    packgesize: 4096
    #IP与端口号配置
    IP:
      #五型
      TFCIP: 127.0.0.1
      #54
      FFOCIP: 127.0.0.1
      #航侦局
      HZJIP: 127.0.0.1
      #中继中心
      ZJIP: 127.0.0.1
      #26长管
      TFMIP: 127.0.0.1
      #26站网
      TFSIP: 127.0.0.1
    PORT:
      TFCudf: 1201
      FFOCudf: 1202
      localHzjUdf: 12301



# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true # we use gulp + BrowserSync for livereload
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/jeecg-boot?useUnicode=true&characterEncoding=utf-8&useSSL=true
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: pkan
    password: nc.plan
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath*:/mappings/service/*/*Mapper.xml
  typeAliasesPackage: com.phy.bcs.*.*.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #logic-delete-value: -2
    #logic-not-delete-value: 0
    db-type: oracle
    identifier-quote: "\"%s\""
    #数据库大写下划线转换
    #capital-mode: true
  #    meta-object-handler: com.c503.plan.common.persistence.handler.EntityMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    jdbc-type-for-null: 'NULL'
