server:
  port: 8210

logging:
  file: log/springboot.log
  level:
    com.phy.bcs.service.ifs: debug

camel:
  springboot:
    main-run-controller: true
fileprocess:
  ftp:
    host: localhost
    port: 21
    username: dev
    password: 123456
    scan-delay: 1000
    readerCharset: "UTF-8"
    senderCharset: "UTF-8"
    reader-scanner-enable: true
    sender-scanner-enable: true
    send-local-dir: "./.ftp-send/"
    send-bak-local-dir: "./.ftp-sent-bak/"
    read-temp-local-dir:  "./.ftp-received-temp/"
    read-bak-local-dir:  "./.ftp-received-bak/"
    #send-file-pattern: '^(MPSS_){1}.*'
    send-file-pattern: '^.*_.*_.*_.*'
    #read-file-pattern: '.*(_MPSS_JB17){1}.*'
    read-file-pattern: '^.*_.*_.*'
    #HZJ向内部发送的文件夹
    hzj-send: "/HZJ/FROMHZJ/"
    #HZJ读取的文件夹
    hzj-read: "/HZJ/TOHZJ/"
    #内部向HZJ发送的文件夹
    internal-send-hzj: "/INTERNAL/FROMINTERNAL/HZJ/"
    #五型向26站网发送的文件夹
    tfc-send-26s: "/INTERNAL/FROMINTERNAL/26S/"
    #五型向26长管发送的文件夹
    tfc-send-26m: "/INTERNAL/FROMINTERNAL/26M/"
    #五型向中继中心发送的文件夹
    tfc-send-zj: "/INTERNAL/FROMINTERNAL/ZJ/"
    #五型读取的文件夹
    tfc-read: "/INTERNAL/TO5X/"
    #54读取的文件夹
    ffoc-read: "/INTERNAL/TO54/"
    passive-mode: true
    hzj-ftpserver1:
      servername: ftpserver1
      host: 127.0.0.1
      port: 21
      username: dev
      password: 123456
    hzj-ftpserver2:
      servername: ftpserver2
      host: 127.0.0.1
      port: 21
      username: dev
      password: 123456
    hzj-ftpserver3:
      servername: ftpserver3
      host: 127.0.0.1
      port: 21
      username: dev
      password: 123456
    hzj-ftpserver4:
      servername: ftpserver4
      host: 127.0.0.1
      port: 21
      username: dev
      password: 123456
    hzj-ftpserver5:
      servername: ftpserver4
      host: 127.0.0.1
      port: 21
      username: dev
      password: 123456
    tfc-ftpserver:
      servername: ftcftpserver
      host: 127.0.0.1
      port: 21
      username: dev
      password: 123456
    ffoc-ftpserver:
      servername: ffocftpserver
      host: 127.0.0.1
      port: 21
      username: dev
      password: 123456


net-application:
  #对应五型的任务号
  wxmids:
    - 0x01
    - 0x04
    - 0x02
    - 0x03
  #对应54的任务号
  wsmids:
    - 0x1001
    - 0x1002
    - 0x1003
    - 0x1004
  #根据该参数判断当前的网络状态
  netstatustimes: 5
  #重连次数
  reconnectTimes: 10
  #超时时间（秒）
  timeout: 30
  #包大小（字节数）
  packgesize: 1024
  #五型IP与端口号配置
  tfc-system:
    ip: 172.0.0.1
    udf-port: 10003
    fep-port: 10003
    pdxp-port: 10003
  #54控制系统IP与端口号配置
  ffoc-system:
    ip: 127.0.0.1
    udf-port: 10001
    fep-port: 10001
    pdxp-port: 10001
  #26站网IP与端口号配置
  tss-system:
    ip: 127.0.0.1
    udf-port: 10004
    fep-port: 10004
    pdxp-port: 10004
  #HZJ IP与端口号配置
  hzj-system:
    ip: 172.0.0.1
    udf-port: 12301
    fep-port: 12302
    pdxp-port: 12303
  #26长管IP与端口号配置
  tsm-system:
    ip: 127.0.0.1
    udf-port: 10002
    fep-port: 10002
    pdxp-port: 10002
  #中继中心IP与端口号配置
  zj-system:
    ip: 10.11.11.161
    udf-port: 10005
    fep-port: 10005
    pdxp-port: 10005
  local-hzj-udfport: 12304
  local-tsm-fepport: 12305
  local-tsm-pdxpport: 12306
  local-tss-fepport: 12307
  local-zj-fepport: 12308
